'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class job_quote
    
    '''<summary>
    '''txtCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEngineer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtJobNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtExvat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExvat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOrderTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlqty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlqty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlcost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlcost As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlhrs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlhrs As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAdditional As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCharge As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdditional As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnsum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnsum As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''grdLabour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdLabour As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''grdPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPart As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ddlqty1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlqty1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCostPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCostPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSellPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSellPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPartNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddpart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddpart As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtAreaDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSupplier As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RptJobList3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RptJobList3 As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtQuoteNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtQuoteEnquiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteEnquiryDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLabour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabour As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParts As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdditional As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddldays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddldays As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmail As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdopreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdopreview As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdoEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoEmail As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''btnEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnCid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnInvestigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInvestigation As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnLabour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnLabour As Global.System.Web.UI.WebControls.HiddenField
End Class
