'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class job_Quote_Print
    
    '''<summary>
    '''frm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtcompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtStreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStreet As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTown As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtasset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtasset As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtmodel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmodel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtappliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtappliance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtquotenumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtquotenumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtquoteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtquoteDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtfault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtffnos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtffnos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtref As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtpremises control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpremises As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grdLabour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdLabour As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblLabourTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabourTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grdParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdParts As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblPartTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalExVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalExVat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalVat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalIncVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalIncVat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVat As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbldays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldays As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnCid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCid As Global.System.Web.UI.WebControls.HiddenField
End Class
