'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Main
    
    '''<summary>
    '''job1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''job11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job11 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''EngSheet1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EngSheet1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''EngSheet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EngSheet2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''EngSheet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EngSheet3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''partorder9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partorder9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''report1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents report1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''report2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents report2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''report3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents report3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''report4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents report4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''hdnToastId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnToastId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnClickJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnClickJob As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnClickPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnClickPart As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnClickPartEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnClickPartEditor As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
