'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Parts_Order_Price_Check
    
    '''<summary>
    '''txtsupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsupplier As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTotalCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalCost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''grdPriceCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPriceCheck As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''grdSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSupplier As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hdnPartid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPartid As Global.System.Web.UI.WebControls.HiddenField
End Class
